import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Coverage from '../components/Coverage'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Plans from '../components/Plans'

const Home: NextPage = () => {
  return (
    <>
    <Head>
      <title>SegurosPromo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>

      <Header />
      <Hero />
      <Plans />
      <Coverage />
    </>
  )
}

export default Home
